# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9be4cf0da3fb46cd1c1222cc70ae2332538d6f091460cecd7c926f80a7ce769697ab2f27f61da523f64204ab20ebeda94280c22a73a8c2aec0e516152595bf2

test:
  secret_key_base: 817b58e0b48da626354d5e38203d8cf26505c6f81e4b2d6c370e1e8383a8d9187b9171b44ac8329eb9b3516acdb3cb2a1d08cb8a3b430225d946c002d0a6a2a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
